services:
  - type: web
    name: resume-ai-analyzer-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: resume-ai-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: CORS_ORIGIN
        value: https://your-frontend-domain.vercel.app

databases:
  - name: resume-ai-db
    plan: free
    region: oregon
    databaseName: resume_ai_analyzer
    user: resume_user
