services:
  - type: web
    name: resume-ai-analyzer-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: CORS_ORIGIN
        value: https://your-frontend-domain.vercel.app
